### ISSUE TITLE
pip install crashes

### ISSUE THREAD

**Issue by unhammer** [rattboi/mopidy-subsonic#16]
with this output
[pip.log.txt](https://github.com/rattboi/mopidy-subsonic/files/121569/pip.log.txt)

**Comment by jodal** [comment]
The crash seems to not be in Mopidy-Subsonic, but in the dependency py-sonic, which tries to do its own HTTP and SSL handling, and fails because modern SSL implementations has SSLv3 entirely turned off for security reasons.

**Comment by crustymonkey** [comment]
I've revamped the py-sonic SSL protocol discovery in 0.4.1 such that it should just work. It starts with a test of the most up to date method (TLS v1.2 as of this writing) and works it's way down from there.  Since this is now based on reflection for protocol discovery, this should just work on any machine and be fully forward compatible.

**Comment by crustymonkey** [comment]
Also, sorry about the wait on this.  Work has been extremely busy of late and I haven't had much time for personal projects.

**Comment by unhammer** [comment]
Thanks, installs fine now :-)
